steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'HF_TOKEN=${_HF_TOKEN}'
      - '-t'
      - 'us-central1-docker.pkg.dev/project-30380897-d50e-4cb6-b3d/cellemetry-repo/cellemetry-agent'
      - '.'
    timeout: 1800s
    
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'us-central1-docker.pkg.dev/project-30380897-d50e-4cb6-b3d/cellemetry-repo/cellemetry-agent'

substitutions:
  _HF_TOKEN: ''

images:
  - 'us-central1-docker.pkg.dev/project-30380897-d50e-4cb6-b3d/cellemetry-repo/cellemetry-agent'

options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100